import SwiftUI
import AppKit

let brand = Color(red: 0.36, green: 0.30, blue: 0.92)

/// The running app's version (from the bundle's CFBundleShortVersionString).
let appVersion: String = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "dev"

/// Notes generated by an app version older than this are flagged for
/// re-generation, because this version changed the summary structure/quality.
/// Bump this whenever a release meaningfully changes generated-note output.
/// Bumped through 0.20.1: VAD (0.13), paragraphs (0.14), timeline (0.15),
/// Obsidian embeds + tags (0.17), and the big summary fixes - full-context
/// summaries (0.20.0) and reliable section/format + language (0.20.1) - all
/// changed note output, so anything older is worth re-generating.
let noteQualityBaseline = "0.20.1"

/// Compare two dotted versions ("0.3.2"). Returns -1, 0, or 1.
func semverCompare(_ a: String, _ b: String) -> Int {
	let pa = a.split(separator: ".").map { Int($0) ?? 0 }
	let pb = b.split(separator: ".").map { Int($0) ?? 0 }
	for i in 0..<max(pa.count, pb.count) {
		let x = i < pa.count ? pa[i] : 0
		let y = i < pb.count ? pb[i] : 0
		if x != y { return x < y ? -1 : 1 }
	}
	return 0
}

/// A note is "outdated" when it has no recorded version (pre-versioning) or its
/// version predates the quality baseline.
func noteIsOutdated(_ noteVersion: String?) -> Bool {
	guard let v = noteVersion, !v.isEmpty, v != "dev" else { return true }
	return semverCompare(v, noteQualityBaseline) < 0
}

/// Languages offered in the record-panel picker.
let meetingLanguages: [(code: String, name: String)] = [
	("auto", "Auto-detect"),
	("en", "English"),
	("uk", "Ukrainian"),
	("pl", "Polish"),
	("hr", "Croatian"),
	("es", "Spanish (Argentina)"),
]

func durationLabel(_ seconds: Int) -> String {
	let h = seconds / 3600, m = (seconds % 3600) / 60, s = seconds % 60
	var parts: [String] = []
	if h > 0 { parts.append("\(h) hr") }
	if m > 0 { parts.append("\(m) min") }
	if s > 0 || parts.isEmpty { parts.append("\(s) sec") }
	return parts.joined(separator: " ")
}
